spring.application.name=atiende

spring.datasource.url=jdbc:mysql://localhost:3306/atiende_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=53062

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false